const actionTypes = {
    GET_POSTS_AJAX_START: 'GET_POSTS_AJAX_START',
    GET_POSTS_AJAX_SUCCESS: 'GET_POSTS_AJAX_SUCCESS',
    GET_POSTS_AJAX_FAILURE: 'GET_POSTS_AJAX_FAILURE',
    GET_POSTS: 'GET_POSTS',

    GET_AUTHORS_AJAX_START: 'GET_AUTHORS_AJAX_START',
    GET_AUTHORS_AJAX_SUCCESS: 'GET_AUTHORS_AJAX_SUCCESS',
    GET_AUTHORS_AJAX_FAILURE: 'GET_AUTHORS_AJAX_FAILURE',
    GET_AUTHORS: 'GET_AUTHORS',
};

export default actionTypes;